# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-ComponentDemo' do
    
  source 'https://github.com/seabrea/SEASpec.git'
  pod 'LocalPrivateLibrary'
  
end
